# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ISX' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
    pod 'Firebase/Core', '4.0.4'
    pod 'Firebase/Database', '4.0.4'
    pod 'Firebase/Messaging', '4.0.4'
    pod 'FirebaseInstanceID', '2.0.0'
	pod 'Firebase/Auth'
    pod 'GoogleAnalytics'
    pod 'NVActivityIndicatorView'
    pod 'PopupDialog', '0.6.2'
  # Pods for ISX

  target 'ISX-CabinCrew' do
      use_frameworks!
      pod 'Firebase/Core', '4.0.4'
      pod 'Firebase/Database', '4.0.4'
      pod 'Firebase/Messaging', '4.0.4'
      pod 'FirebaseInstanceID', '2.0.0'
      pod 'Firebase/Auth'
      pod 'NVActivityIndicatorView'
      pod 'PopupDialog', '0.6.2'

   # Pods for ISX-CabinCrew
  end

end
