# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ISX' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
	pod 'Firebase/Core'
    pod 'Firebase/Database'
	pod 'Firebase/Auth'
    pod 'GoogleAnalytics'
    pod 'NVActivityIndicatorView'
  # Pods for ISX

  target 'ISX-CabinCrew' do
      use_frameworks!
      pod 'Firebase/Core'
      pod 'Firebase/Database'
      pod 'Firebase/Auth'
      pod 'NVActivityIndicatorView'
      
   # Pods for ISX-CabinCrew
  end

end
